"""add notes to calls

Revision ID: 673450cc1c94
Revises: 29d113a84604
Create Date: 2026-04-12 18:48:34.981299
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673450cc1c94'
down_revision: Union[str, None] = '29d113a84604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'notes')
    # ### end Alembic commands ###
