"""add contacts table and call contact_id

Revision ID: 8827db963a60
Revises: b0487876cf11
Create Date: 2026-04-12 18:09:46.970438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8827db963a60'
down_revision: Union[str, None] = 'b0487876cf11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('phone_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('google_contact_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.add_column('calls', sa.Column('contact_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_calls_contact_id'), 'calls', ['contact_id'], unique=False)
    op.create_foreign_key(None, 'calls', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_index(op.f('ix_calls_contact_id'), table_name='calls')
    op.drop_column('calls', 'contact_id')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
