"""add is_superadmin and nullable tenant_id on users

Revision ID: b0487876cf11
Revises: 2b623fce4424
Create Date: 2026-04-12 17:42:51.409398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0487876cf11'
down_revision: Union[str, None] = '2b623fce4424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###
